//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_article")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub cid: String,
    pub title: String,
    pub author: Option<String>,
    pub image_input: String,
    pub synopsis: Option<String>,
    pub share_title: Option<String>,
    pub share_synopsis: Option<String>,
    pub visit: Option<String>,
    pub sort: u32,
    pub url: Option<String>,
    pub media_id: Option<String>,
    pub status: u32,
    pub hide: u32,
    pub admin_id: u32,
    pub mer_id: Option<u32>,
    pub product_id: i32,
    pub is_hot: u32,
    pub is_banner: u32,
    pub content: String,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
