//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub pid: u32,
    pub path: String,
    pub name: String,
    #[sea_orm(column_name = "type")]
    pub r#type: Option<i32>,
    pub url: Option<String>,
    pub extra: Option<String>,
    pub status: i32,
    pub sort: i32,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
