//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_exception_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub exp_url: Option<String>,
    pub exp_params: Option<String>,
    pub exp_type: Option<String>,
    pub exp_controller: Option<String>,
    pub exp_method: Option<String>,
    pub exp_detail: Option<String>,
    pub create_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
