//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_express")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub code: String,
    pub name: String,
    pub partner_id: i32,
    pub partner_key: i32,
    pub net: i32,
    pub account: String,
    pub password: String,
    pub net_name: String,
    pub sort: i32,
    pub is_show: i32,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
