//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_page_diy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: String,
    pub name: String,
    pub title: String,
    pub cover_image: String,
    pub template_name: String,
    pub value: Option<String>,
    pub add_time: DateTime,
    pub update_time: DateTime,
    pub status: i32,
    #[sea_orm(column_name = "type")]
    pub r#type: i32,
    pub is_show: i32,
    pub is_bg_color: i32,
    pub is_bg_pic: i32,
    pub is_diy: i32,
    pub color_picker: String,
    pub bg_pic: String,
    pub bg_tab_val: i32,
    pub is_del: i32,
    pub return_address: String,
    pub title_bg_color: String,
    pub title_color: String,
    pub service_status: i32,
    pub mer_id: i32,
    pub is_default: i32,
    pub text_position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
