//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_page_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: i32,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub name: String,
    pub sort: i32,
    pub status: i32,
    pub add_time: DateTime,
    pub level: i32,
    pub is_mer: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
