//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_schedule_job")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub job_id: i32,
    pub bean_name: Option<String>,
    pub method_name: Option<String>,
    pub params: Option<String>,
    pub cron_expression: Option<String>,
    pub status: Option<i32>,
    pub remark: Option<String>,
    pub is_delte: Option<u32>,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
