//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_shipping_templates_free")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub temp_id: i32,
    pub city_id: i32,
    pub title: Option<String>,
    pub number: Decimal,
    pub price: Decimal,
    #[sea_orm(column_name = "type")]
    pub r#type: i32,
    pub uniqid: String,
    pub status: Option<i32>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
