//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_sms_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub uid: String,
    pub phone: String,
    pub content: Option<String>,
    pub add_ip: Option<String>,
    pub create_time: Option<DateTime>,
    pub template: Option<String>,
    pub resultcode: Option<u32>,
    pub record_id: Option<u32>,
    pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
