//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_sms_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub temp_id: String,
    pub temp_type: i32,
    pub title: String,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub temp_key: String,
    pub status: i32,
    pub content: String,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
