//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_pink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: i32,
    pub order_id: String,
    pub order_id_key: i32,
    pub total_num: i32,
    pub total_price: Decimal,
    pub cid: i32,
    pub pid: i32,
    pub people: i32,
    pub price: Decimal,
    pub add_time: i64,
    pub stop_time: i64,
    pub k_id: i32,
    pub is_tpl: i16,
    pub is_refund: i16,
    pub status: i16,
    pub is_virtual: i16,
    pub nickname: String,
    pub avatar: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
