//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub product_id: i32,
    pub uid: i32,
    pub visit_num: i32,
    pub cart_num: i32,
    pub order_num: i32,
    pub pay_num: i32,
    pub pay_price: Decimal,
    pub cost_price: Decimal,
    pub pay_uid: i32,
    pub refund_num: i32,
    pub refund_price: Decimal,
    pub collect_num: i32,
    pub add_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
