//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mer_id: i32,
    pub image: String,
    pub slider_image: String,
    pub store_name: String,
    pub store_info: String,
    pub keyword: String,
    pub bar_code: String,
    pub cate_id: String,
    pub price: Decimal,
    pub vip_price: Decimal,
    pub ot_price: Decimal,
    pub postage: Decimal,
    pub unit_name: String,
    pub sort: i16,
    pub sales: i32,
    pub stock: i32,
    pub is_show: i16,
    pub is_hot: i16,
    pub is_benefit: i16,
    pub is_best: i16,
    pub is_new: i16,
    pub add_time: i32,
    pub is_postage: i16,
    pub is_del: i16,
    pub mer_use: i16,
    pub give_integral: Option<i32>,
    pub cost: Decimal,
    pub is_seckill: i16,
    pub is_bargain: Option<i16>,
    pub is_good: i16,
    pub is_sub: i16,
    pub ficti: Option<i32>,
    pub browse: Option<i32>,
    pub code_path: String,
    pub soure_link: Option<String>,
    pub video_link: String,
    pub temp_id: i32,
    pub spec_type: i16,
    pub activity: String,
    pub flat_pattern: String,
    pub is_recycle: i16,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
