//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub order_id: String,
    pub uid: u32,
    pub real_name: String,
    pub user_phone: String,
    pub user_address: String,
    pub freight_price: Decimal,
    pub total_num: u32,
    pub total_price: Decimal,
    pub total_postage: Decimal,
    pub pay_price: Decimal,
    pub pay_postage: Decimal,
    pub deduction_price: Decimal,
    pub coupon_id: u32,
    pub coupon_price: Decimal,
    pub paid: u32,
    pub pay_time: Option<DateTime>,
    pub pay_type: String,
    pub create_time: Option<DateTime>,
    pub status: i32,
    pub refund_status: u32,
    pub refund_reason_wap_img: Option<String>,
    pub refund_reason_wap_explain: Option<String>,
    pub refund_reason_wap: Option<String>,
    pub refund_reason: Option<String>,
    pub refund_reason_time: Option<DateTime>,
    pub refund_price: Decimal,
    pub delivery_name: Option<String>,
    pub delivery_type: Option<String>,
    pub delivery_id: Option<String>,
    pub gain_integral: Option<i32>,
    pub use_integral: Option<i32>,
    pub back_integral: Option<i32>,
    pub mark: String,
    pub is_del: u32,
    pub remark: Option<String>,
    pub mer_id: u32,
    pub is_mer_check: u32,
    pub combination_id: Option<u32>,
    pub pink_id: u32,
    pub cost: Decimal,
    pub seckill_id: u32,
    pub bargain_id: Option<u32>,
    pub verify_code: String,
    pub store_id: i32,
    pub shipping_type: i32,
    pub clerk_id: i32,
    pub is_channel: Option<u32>,
    pub is_remind: Option<u32>,
    pub is_system_del: Option<i32>,
    pub update_time: DateTime,
    pub delivery_code: Option<String>,
    pub bargain_user_id: u32,
    #[sea_orm(column_name = "type")]
    pub r#type: i32,
    pub pro_total_price: Decimal,
    pub before_pay_price: Decimal,
    pub is_alter_price: i32,
    pub out_trade_no: Option<String>,
    pub shipment_pic: Option<String>,
    pub shipment_task_id: Option<String>,
    pub shipment_order_id: Option<String>,
    pub shipment_num: Option<String>,
    pub express_record_type: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
