//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mer_id: u32,
    pub image: String,
    pub slider_image: String,
    pub store_name: String,
    pub store_info: String,
    pub keyword: String,
    pub bar_code: String,
    pub cate_id: String,
    pub price: Decimal,
    pub vip_price: Decimal,
    pub ot_price: Decimal,
    pub postage: Decimal,
    pub unit_name: String,
    pub sort: i32,
    pub sales: u32,
    pub stock: u32,
    pub is_show: i32,
    pub is_hot: i32,
    pub is_benefit: i32,
    pub is_best: i32,
    pub is_new: i32,
    pub add_time: u32,
    pub is_postage: u32,
    pub is_del: u32,
    pub mer_use: u32,
    pub give_integral: Option<i32>,
    pub cost: Decimal,
    pub is_seckill: u32,
    pub is_bargain: Option<u32>,
    pub is_good: i32,
    pub is_sub: i32,
    pub ficti: Option<i32>,
    pub browse: Option<i32>,
    pub code_path: String,
    pub soure_link: Option<String>,
    pub video_link: String,
    pub temp_id: i32,
    pub spec_type: i32,
    pub activity: String,
    pub flat_pattern: String,
    pub is_recycle: i32,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
