//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_coupon_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub coupon_id: i32,
    pub cid: u32,
    pub uid: u32,
    pub name: String,
    pub money: Decimal,
    pub min_price: Decimal,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub status: i32,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub use_time: Option<DateTime>,
    pub use_type: Option<i32>,
    pub primary_key: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
