//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product_attr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: u32,
    pub attr_name: String,
    pub attr_values: String,
    #[sea_orm(column_name = "type")]
    pub r#type: Option<i32>,
    pub is_del: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
