//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_order_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub order_id: u32,
    pub product_id: u32,
    pub info: String,
    pub unique: String,
    pub create_time: Option<DateTime>,
    pub update_time: DateTime,
    pub order_no: String,
    pub product_name: String,
    pub attr_value_id: Option<u32>,
    pub image: String,
    pub sku: String,
    pub price: Decimal,
    pub pay_num: u32,
    pub weight: Decimal,
    pub volume: Decimal,
    pub give_integral: u32,
    pub is_reply: i32,
    pub is_sub: i32,
    pub vip_price: Decimal,
    pub product_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
