//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_bargain_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: Option<u32>,
    pub bargain_id: Option<u32>,
    pub bargain_price_min: Option<Decimal>,
    pub bargain_price: Option<Decimal>,
    pub price: Option<Decimal>,
    pub status: u32,
    pub add_time: Option<u64>,
    pub is_del: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
