//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_bargain_user_help")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: Option<i32>,
    pub bargain_id: Option<i32>,
    pub bargain_user_id: Option<i32>,
    pub price: Option<Decimal>,
    pub add_time: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
