//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product_reply")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: i32,
    pub oid: i32,
    pub unique: String,
    pub product_id: i32,
    pub reply_type: String,
    pub product_score: i32,
    pub service_score: i32,
    pub comment: String,
    pub pics: String,
    pub merchant_reply_content: Option<String>,
    pub merchant_reply_time: Option<i32>,
    pub is_del: u32,
    pub is_reply: i32,
    pub nickname: String,
    pub avatar: String,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub sku: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
