//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_bargain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: u32,
    pub title: String,
    pub image: String,
    pub unit_name: Option<String>,
    pub stock: Option<u32>,
    pub sales: Option<u32>,
    pub images: String,
    pub start_time: u64,
    pub stop_time: u64,
    pub store_name: Option<String>,
    pub price: Option<Decimal>,
    pub min_price: Option<Decimal>,
    pub num: Option<u32>,
    pub bargain_max_price: Option<Decimal>,
    pub bargain_min_price: Option<Decimal>,
    pub bargain_num: u32,
    pub status: u32,
    pub give_integral: Option<i32>,
    pub info: Option<String>,
    pub cost: Option<Decimal>,
    pub sort: u32,
    pub is_hot: u32,
    pub is_del: u32,
    pub add_time: Option<u64>,
    pub is_postage: u32,
    pub postage: Option<Decimal>,
    pub rule: Option<String>,
    pub look: Option<u32>,
    pub share: Option<u32>,
    pub temp_id: Option<i32>,
    pub weight: Option<Decimal>,
    pub volume: Option<Decimal>,
    pub quota: i32,
    pub quota_show: i32,
    pub people_num: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
