//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_coupon")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub money: Decimal,
    pub is_limited: Option<i16>,
    pub total: i32,
    pub last_total: Option<i32>,
    pub use_type: i16,
    pub primary_key: String,
    pub min_price: Decimal,
    pub receive_start_time: DateTime,
    pub receive_end_time: Option<DateTime>,
    pub is_fixed_time: Option<i16>,
    pub use_start_time: Option<DateTime>,
    pub use_end_time: Option<DateTime>,
    pub day: Option<i32>,
    #[sea_orm(column_name = "type")]
    pub r#type: i16,
    pub sort: i32,
    pub status: i16,
    pub is_del: i16,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
