//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_pink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: u32,
    pub order_id: String,
    pub order_id_key: u32,
    pub total_num: u32,
    pub total_price: Decimal,
    pub cid: u32,
    pub pid: u32,
    pub people: u32,
    pub price: Decimal,
    pub add_time: i64,
    pub stop_time: i64,
    pub k_id: u32,
    pub is_tpl: u32,
    pub is_refund: u32,
    pub status: u32,
    pub is_virtual: i32,
    pub nickname: String,
    pub avatar: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
