//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_seckill")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: u32,
    pub image: String,
    pub images: String,
    pub title: String,
    pub info: String,
    pub price: Decimal,
    pub cost: Decimal,
    pub ot_price: Decimal,
    pub give_integral: Decimal,
    pub sort: u32,
    pub stock: u32,
    pub sales: u32,
    pub unit_name: String,
    pub postage: Decimal,
    pub description: Option<String>,
    pub start_time: DateTime,
    pub stop_time: DateTime,
    pub create_time: DateTime,
    pub status: u32,
    pub is_postage: u32,
    pub is_del: u32,
    pub num: u32,
    pub is_show: u32,
    pub time_id: Option<i32>,
    pub temp_id: i32,
    pub weight: Decimal,
    pub volume: Decimal,
    pub quota: i32,
    pub quota_show: i32,
    pub spec_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
