//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_product_attr_value")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: u32,
    pub suk: String,
    pub stock: u32,
    pub sales: u32,
    pub price: Decimal,
    pub image: Option<String>,
    pub unique: String,
    pub cost: Decimal,
    pub bar_code: String,
    pub ot_price: Decimal,
    pub weight: Decimal,
    pub volume: Decimal,
    pub brokerage: Decimal,
    pub brokerage_two: Decimal,
    #[sea_orm(column_name = "type")]
    pub r#type: Option<i32>,
    pub quota: Option<i32>,
    pub quota_show: Option<i32>,
    pub attr_value: Option<String>,
    pub is_del: i32,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
