//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_cart")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub uid: u32,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub product_id: u32,
    pub product_attr_unique: String,
    pub cart_num: u32,
    pub is_new: i32,
    pub combination_id: Option<u32>,
    pub seckill_id: u32,
    pub bargain_id: u32,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
