//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_store_combination")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: i32,
    pub mer_id: Option<i32>,
    pub image: String,
    pub images: String,
    pub title: String,
    pub attr: Option<String>,
    pub people: i32,
    pub info: String,
    pub price: Decimal,
    pub sort: i32,
    pub sales: i32,
    pub stock: i32,
    pub add_time: i64,
    pub is_host: i16,
    pub is_show: i16,
    pub is_del: i16,
    pub combination: Option<i16>,
    pub mer_use: Option<i16>,
    pub is_postage: Option<i16>,
    pub postage: Option<Decimal>,
    pub start_time: i64,
    pub stop_time: i64,
    pub effective_time: i32,
    pub cost: Decimal,
    pub browse: Option<i32>,
    pub unit_name: String,
    pub temp_id: i32,
    pub weight: Option<Decimal>,
    pub volume: Option<Decimal>,
    pub num: Option<i32>,
    pub quota: i32,
    pub quota_show: i32,
    pub ot_price: Decimal,
    pub once_num: i32,
    pub virtual_ration: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
