//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_system_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: u32,
    pub name: Option<String>,
    pub icon: Option<String>,
    pub perms: Option<String>,
    pub component: Option<String>,
    pub menu_type: Option<String>,
    pub sort: i32,
    pub is_show: i32,
    pub is_delte: Option<u32>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
