//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_system_notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mark: String,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub description: String,
    pub is_wechat: i32,
    pub wechat_id: i32,
    pub is_routine: i32,
    pub routine_id: i32,
    pub is_sms: i32,
    pub sms_id: i32,
    pub send_type: i32,
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
