//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_system_store_staff")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub uid: u32,
    pub avatar: String,
    pub store_id: i32,
    pub staff_name: Option<String>,
    pub phone: Option<String>,
    pub verify_status: i32,
    pub status: Option<i32>,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
