//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_system_attachment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub att_id: i32,
    pub name: String,
    pub att_dir: String,
    pub satt_dir: Option<String>,
    pub att_size: String,
    pub att_type: String,
    pub pid: i32,
    pub image_type: u32,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
