//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_system_admin")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    pub account: String,
    pub pwd: String,
    pub real_name: String,
    pub roles: String,
    pub last_ip: Option<String>,
    pub update_time: DateTime,
    pub create_time: DateTime,
    pub login_count: u32,
    pub level: u32,
    pub status: u32,
    pub is_del: u32,
    pub phone: Option<String>,
    pub is_sms: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
