//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_extract")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub uid: Option<u32>,
    pub real_name: Option<String>,
    pub extract_type: Option<String>,
    pub bank_code: Option<String>,
    pub bank_address: Option<String>,
    pub alipay_code: Option<String>,
    pub extract_price: Option<Decimal>,
    pub mark: Option<String>,
    pub balance: Option<Decimal>,
    pub fail_msg: Option<String>,
    pub status: Option<i32>,
    pub wechat: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub fail_time: Option<DateTime>,
    pub bank_name: Option<String>,
    pub qrcode_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
