//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub uid: u32,
    pub account: String,
    pub pwd: Option<String>,
    pub real_name: Option<String>,
    pub birthday: Option<String>,
    pub card_id: Option<String>,
    pub mark: Option<String>,
    pub partner_id: Option<i32>,
    pub group_id: Option<String>,
    pub tag_id: Option<String>,
    pub nickname: Option<String>,
    pub avatar: Option<String>,
    pub phone: Option<String>,
    pub add_ip: Option<String>,
    pub last_ip: Option<String>,
    pub now_money: Option<Decimal>,
    pub brokerage_price: Option<Decimal>,
    pub integral: Option<i32>,
    pub experience: Option<u32>,
    pub sign_num: Option<i32>,
    pub status: Option<i32>,
    pub level: Option<u32>,
    pub spread_uid: Option<u32>,
    pub spread_time: Option<DateTime>,
    pub user_type: String,
    pub is_promoter: Option<u32>,
    pub pay_count: Option<u32>,
    pub spread_count: Option<i32>,
    pub addres: Option<String>,
    pub adminid: Option<u32>,
    pub login_type: String,
    pub create_time: DateTime,
    pub update_time: DateTime,
    pub last_login_time: Option<DateTime>,
    pub clean_time: Option<DateTime>,
    pub path: String,
    pub subscribe: Option<i32>,
    pub subscribe_time: Option<DateTime>,
    pub sex: Option<i32>,
    pub country: Option<String>,
    pub promoter_time: Option<DateTime>,
    pub is_logoff: i32,
    pub logoff_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
