//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_recharge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: Option<i32>,
    pub order_id: Option<String>,
    pub price: Option<Decimal>,
    pub give_price: Decimal,
    pub recharge_type: Option<String>,
    pub paid: Option<i32>,
    pub pay_time: Option<DateTime>,
    pub create_time: Option<DateTime>,
    pub refund_price: Option<Decimal>,
    pub is_wechat_shipping: i32,
    pub out_trade_no: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
