//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_brokerage_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: i32,
    pub link_id: String,
    pub link_type: String,
    #[sea_orm(column_name = "type")]
    pub r#type: i32,
    pub title: String,
    pub price: Decimal,
    pub balance: Decimal,
    pub mark: String,
    pub status: i32,
    pub frozen_time: i32,
    pub thaw_time: i64,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub brokerage_level: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
