//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use rust_decimal::Decimal;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_bill")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub uid: u32,
    pub link_id: String,
    pub pm: u32,
    pub title: String,
    pub category: String,
    #[sea_orm(column_name = "type")]
    pub r#type: String,
    pub number: Decimal,
    pub balance: Decimal,
    pub mark: String,
    pub status: i32,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
