//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_address")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: u32,
    pub real_name: String,
    pub phone: String,
    pub province: String,
    pub city: String,
    pub city_id: i32,
    pub district: String,
    pub detail: String,
    pub post_code: i32,
    pub longitude: String,
    pub latitude: String,
    pub is_default: u32,
    pub is_del: u32,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
