//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_user_token")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: u32,
    pub token: String,
    #[sea_orm(column_name = "type")]
    pub r#type: Option<i32>,
    pub create_time: DateTime,
    pub expires_time: Option<DateTime>,
    pub login_ip: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
