//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_wechat_callback")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub to_user_name: Option<String>,
    pub from_user_name: Option<String>,
    pub create_time: Option<u64>,
    pub msg_type: Option<String>,
    pub event: Option<String>,
    pub content: Option<String>,
    pub add_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
