//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_wechat_program_my_temp")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub tid: i32,
    pub title: String,
    pub kid: String,
    pub scene_desc: String,
    pub temp_id: Option<String>,
    pub extra: Option<String>,
    pub status: i32,
    #[sea_orm(column_name = "type")]
    pub r#type: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
