//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ty_wechat_pay_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub app_id: Option<String>,
    pub mch_id: Option<String>,
    pub device_info: Option<String>,
    pub open_id: Option<String>,
    pub nonce_str: Option<String>,
    pub sign: Option<String>,
    pub sign_type: Option<String>,
    pub body: Option<String>,
    pub detail: Option<String>,
    pub attach: Option<String>,
    pub out_trade_no: Option<String>,
    pub fee_type: Option<String>,
    pub total_fee: Option<i32>,
    pub spbill_create_ip: Option<String>,
    pub time_start: Option<String>,
    pub time_expire: Option<String>,
    pub notify_url: Option<String>,
    pub trade_type: Option<String>,
    pub product_id: Option<String>,
    pub scene_info: Option<String>,
    pub err_code: Option<String>,
    pub prepay_id: Option<String>,
    pub code_url: Option<String>,
    pub is_subscribe: Option<String>,
    pub trade_state: Option<String>,
    pub bank_type: Option<String>,
    pub cash_fee: Option<i32>,
    pub coupon_fee: Option<i32>,
    pub transaction_id: Option<String>,
    pub time_end: Option<String>,
    pub trade_state_desc: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
